{{ if eq .Values.dex.istio.enabled true }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-all-allow-access
  namespace: {{ .Release.Namespace }}
  labels: {{ include "dex.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-allow-external-access
  namespace: {{ .Values.dex.istio.namespace }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  rules:
  - to:
    - operation:
        hosts:
        - {{ .Values.dex.istio.host }}
{{ end }}
