# Default values for profile-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  istioNamespace: istio
  clusterDomain: cluster.local
  userIDHeader: kubeflow-userid
  userIDPrefix: ""
  oidcIssuer: https://oidc.plural.sh/
  jwksURI: https://oidc.plural.sh/.well-known/jwks.json

image:
  repository: ghcr.io/pluralsh/kubeflow-profile-controller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.1.10

kfam:
  image:
    repository: davidspek/kfam
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.1.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "true"
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  prometheus.io/port: "8080"
  prometheus.io/scheme: http
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

config:
  infrastructure:
    clusterName: kubeflow-dev
    provider: AWS
    providerConfig:
      accountID: "332124921534"
      region: us-east-2
      clusterOIDCIssuer: "https://oidc.eks.us-east-2.amazonaws.com/id/50C07702B65D541BF8CA91958886A04A"
    storage:
      provider: S3
      bucketName: kubeflow-dev-pipelines-new
  namespace:
    defaultLabels:
      katib-metricscollector-injection:      'enabled'
      serving.kubeflow.org/inferenceservice: 'enabled'
      pipelines.kubeflow.org/enabled:        'true'
  network:
    hostname: kubeflow.kubeflow-aws.com
    clusterDomain: cluster.local
    istio:
      clusterGateway:
        name: kubeflow-gateway
        namespace: kubeflow
  security:
    oidc:
      issuer: https://oidc.plural.sh/
      jwksURI: https://oidc.plural.sh/.well-known/jwks.json
  identity:
    userIdPrefix: ""

service:
  controller:
    port: 8080
  kfam:
    port: 8082

virtualService:
  annotations: {}
  prefix: /kfam
  gateways:
    - kubeflow-gateway
  hosts:
    - '*'

resources:
  requests:
    cpu: 11m
    memory: 70Mi
  limits:
    cpu: 11m
    memory: 70Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
