apiVersion: v2
name: crossplane
description: A Helm chart for Kubernetes
type: application
version: 0.1.11
appVersion: "1.6.3"
dependencies:
- name: crossplane
  version: 1.6.3
  repository: https://charts.crossplane.io/stable
