kyverno:
  installCRDs: false
  image:
    repository: dkr.plural.sh/kyverno/kyverno/kyverno
  initImage:
    repository: dkr.plural.sh/kyverno/kyverno/kyvernopre
  serviceAccount:
    create: true
  serviceMonitor:
    enabled: true
kyverno-policies:
  enabled: false
