apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  application: true
  description: Deploys renovate crafted for the target cloud
spec:
  dependencies:
  - type: helm
    name: bootstrap
    repo: bootstrap
    version: '>= 0.5.1'
  
  
  - type: terraform
    name: aws
    repo: renovate
    version: '>= 0.1.0'
    optional: true
  - type: terraform
    name: azure
    repo: renovate
    version: '>= 0.1.0'
    optional: true
  - type: terraform
    name: gcp
    repo: renovate
    version: '>= 0.1.0'
    optional: true