renovate:
  serviceAccount:
    create: true
  apiVersionOverrides:
    cronjob: 'batch/v1'
  renovate:
    config: |
      {
        "platform": "github,
        "autodiscover": "true",
        "dryRun": "true",
        "printConfig": true
      }
