apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-ceph-objectstore-external
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.s3Hostname }}
  labels:
    {{- include "rook.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    app: rook-ceph-rgw
    ceph_daemon_id: ceph-objectstore
    rgw: ceph-objectstore
    rook_cluster: rook
    rook_object_store: ceph-objectstore
  type: LoadBalancer
