apiVersion: v2
name: airbyte
description: Unified data integration platform
type: application
version: 0.2.17
appVersion: "1.16.0"
dependencies:
- name: airbyte
  version: 0.3.0
- name: oidc-config
  version: 0.1.6
  repository: https://pluralsh.github.io/module-library
  condition: oidc-config.enabled
