apiVersion: v2
name: airbyte
description: Unified data integration platform
type: application
version: 0.1.24
appVersion: "1.16.0"
dependencies:
- name: airbyte
  version: 0.3.0
  repository: file://../../../../airbyte/charts/airbyte
